-- MySQL Script generated by MySQL Workbench
-- Sun Dec 19 15:45:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gjfarma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gjfarma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gjfarma` DEFAULT CHARACTER SET utf8 ;
USE `gjfarma` ;

-- -----------------------------------------------------
-- Table `gjfarma`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gjfarma`.`rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`rols` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gjfarma`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  `avatar` VARCHAR(80) NULL DEFAULT NULL,
  `rol_id` INT(11) NULL DEFAULT NULL,
  `rols_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `rols_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_Users_rols1_idx` (`rols_id` ASC),
  CONSTRAINT `fk_Users_rols1`
    FOREIGN KEY (`rols_id`)
    REFERENCES `gjfarma`.`rols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gjfarma`.`shippings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`shippings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(80) NOT NULL,
  `zip` INT(11) NOT NULL,
  `cost` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gjfarma`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`carts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `shipping_id` INT(11) NULL DEFAULT NULL,
  `Users_id` INT(11) NOT NULL,
  `shippings_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Users_id`, `shippings_id`),
  INDEX `fk_carts_Users_idx` (`Users_id` ASC),
  INDEX `fk_carts_shippings1_idx` (`shippings_id` ASC),
  CONSTRAINT `fk_carts_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `gjfarma`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_shippings1`
    FOREIGN KEY (`shippings_id`)
    REFERENCES `gjfarma`.`shippings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gjfarma`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gjfarma`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gjfarma`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `precio` INT(11) NOT NULL,
  `stock` INT(11) NOT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `brand_id` INT(11) NULL DEFAULT NULL,
  `image_id` INT(11) NULL DEFAULT NULL,
  `images_id` INT(11) NOT NULL,
  `brands_id` INT(11) NOT NULL,
  `categories_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `images_id`, `brands_id`, `categories_id`),
  INDEX `fk_products_images1_idx` (`images_id` ASC),
  INDEX `fk_products_brands1_idx` (`brands_id` ASC),
  INDEX `fk_products_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_products_brands1`
    FOREIGN KEY (`brands_id`)
    REFERENCES `gjfarma`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `gjfarma`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `gjfarma`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gjfarma`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjfarma`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NULL DEFAULT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `cart_id` INT(11) NULL DEFAULT NULL,
  `carts_id` INT(11) NOT NULL,
  `carts_Users_id` INT(11) NOT NULL,
  `carts_shippings_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `carts_id`, `carts_Users_id`, `carts_shippings_id`, `products_id`),
  INDEX `fk_orders_carts1_idx` (`carts_id` ASC, `carts_Users_id` ASC, `carts_shippings_id` ASC),
  INDEX `fk_orders_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_orders_carts1`
    FOREIGN KEY (`carts_id` , `carts_Users_id` , `carts_shippings_id`)
    REFERENCES `gjfarma`.`carts` (`id` , `Users_id` , `shippings_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `gjfarma`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
